platform :ios, '15.0'
use_frameworks!

target 'iosApp' do
  pod 'FirebaseCore'
  pod 'FirebaseCrashlytics'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
      config.build_settings['CODE_SIGNING_REQUIRED'] = 'NO'
    end
  end
end
